apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: izik-stg-new_app_2
  namespace: argocd

  labels:
    tenant: izik
    lifecycle: stg

spec:
  project: izik-stg

  source:
    repoURL: string
    targetRevision: master
    path: string


  destination:
    server: server
    namespace: izik-stg-new_app_2

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true