apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: izik-prd-new_app
  namespace: argocd

  labels:
    tenant: izik
    lifecycle: prd

spec:
  project: izik-prd

  source:
    repoURL: string
    targetRevision: master
    path: string


  destination:
    server: server
    namespace: izik-prd-new_app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true